### PR TITLE
Engine overhaul

### PR DESCRIPTION
**Pull request by FirebrandCoding**
I've been working on this version of the game for a bit since first seeing it on the incremental games subreddit. The code looked a mess, so I've decided to spend time to clean it and optimize it. Nothing against learners and beginners: just wanted to show you what could be done.

Don't merge the two versions: look at mine and check out what I've done. It's not perfect, and there are things I see could be done, but it features some fairly advanced practices already that you could learn from. Feel free to do with the code whatever you want: incorporate, change, discard... It's a learner's material, nothing more. Coding it helped me through a tough time of exams, and it felt a shame to just throw the ready product away. If you need any aspect of it explained — feel free to message me.

First of all, I've optimized the data structure for in-game time-telling. Now you have a single object hold the important data that could be easily save into local storage and retrieve (*there can be made argument against having one main object, but I felt it reasonable to categorize them as I did*). On save, the object also receives the time played in the game and the game version it was played in (presented as an array of values modelled after [semantic versioning](https://semver.org/). Ideally, it would feature some sort of a conversion process when loading an older save, but for now any change to major (`version[0]`) or minor (`version[1]`) versions wipes the save and starts the game from scratch.

The game structure is also extendible now. You can add whatever time units you want with only an edit of two variables: the name in `units` and the maximum in `unitsMax` (I sense there's a better way to do this, but so far, it's what I got). All purchases and upgrades is also automated, since, outside of seconds, the process is identical for each. The same idea stands behind many of the loops: there's no reason to use separate variables when you can just juggle through them to the desired effect. You'd still need to modify the HTML of it, but even that could be done with loops and some light variable writing.

The initial idea behind the overhaul was to set the game onto a more responsive railing of `requestAnimationFrame`, which (mostly) works even if the browser tab is in the background. It uses a fairly simple `rAF` timer by Chris Coyier. More powerful alternatives exist, but so far, it seems to suffice for the purpose.

One important aspect of the code that's seriously lacking in the original is easily decypherable variable names. I alleviated that to the best of my ability: most of the fuctions and variables give you a straight idea of what they do or are for. I wasn't able to piece together what `accelDouble` was supposed to mean, so I left it in as is.

The new code has no heavy dependencies like jQuery. The utility functions could be set apart into a separate file so as to not clutter the main codebase.

Good work on taking care of the game, and keep learning!

### CODE REVIEW

**Comment by Phantasy146** [comment]
First of all, before I say anything, thank you. I sense I'm gonna spend A LOT of the next few days reading through this, doing research on the code you used, testing it out, etc.
I will admit that when I noticed there was a new fork, I looked at it and read through it and was like, "Woah... where is the author going with this?"
I just wanna say that before completion of this game there will be a "thank you"s place with you and all the other people who helped me in it.
Thanks again. I really appreciate it.

**Comment by HeinousTugboat** [comment]
Hi! So, I actually saw your fork before too and I was curious about some of the things you were doing. I wasn't sure if you were planning on doing a PR on it or not. I have a couple thoughts I'd like to share.

* So, you query the document for the HTML tags every UI pass. Is there any reason you aren't caching them? Ideally you should cache the DOM in the initialize phase and simply reference back to it instead of performing the query every tick.
* One random thing I'm curious about is your use of `var` vs `let`. I don't see any reason, especially at the top level, for why you would use `var`. I've seen that from a lot of people lately, and I'm wondering if it's just an inconsistency or if there's an actual reason for it.
* The rAF loop you included is.. incredibly strange to me. Why does it return anything if you aren't actually storing that reference? I'd also argue it isn't really necessary to check for backwards compatibility like that. rAF's supported by [93%](https://caniuse.com/#feat=requestanimationframe) of users, and more if you drop mobile.
* Another thing about the loop, it's calculating the dT, which it absolutely should, but the actual tick function doesn't appear to be running on the delta, which is *definitely* should. While you're right, that rAF does work in background tabs, it's harshly throttled to about 1 frame per second vs. the standard 60. If you run on the delta, then the game can move ahead at regular speed even in the background.
* Finally, looking at the save routine, I don't really understand why you're doing it the way you are. Why deep copy the game data instead of just saving it straight to localstorage? Why set the version every save (*and* every tick..)? And there's no reason to calculate played every time you save. Save the timestamp at the start of the session, and the timestamp you're saving at. Then on load you can add the time played. Or any other of a variety of options. Seems unnecessary to call that 60 times per second. (I'd also argue it's unnecessary to save every 17ms, but that's definitely up for debate.) On that note, `Date.now()` is called 5 times in this code, 3 of which happen on every tick.

One last thing, though, I do like the data structure you've gone with here. That seems pretty clean and well done. 👍

**Comment by FirebrandCoding** [comment]
@Phantasy146: you're welcome. With what I do, it's always a gamble on whether the person would appreciate what I have to give or will arrogantly reject it. I'm not saying I'm great or anything, but sometimes people react aggressively towards "trying to mess" with their work. I'm glad you're from the more reasonable folk.

Like I said, feel free to contact me with the questions you might have. Also — not sure if you know already — Mozilla Developer Network (MDN) is a fantastic source of information on all things frontend-dev. If you want to find out about a certain HTML-, CSS- or JS-property, just search for "mdn <name of property>".

@HeinousTugboat:

1. Yes, caching the UI and only changing the updated values would be great. I was attempting to do so, before giving up. The process seemed far too complicated for me. I'm sure it's actually very simple, but I've done nothing like that before. If the game dev managed to do so, it would be a great advantage to the game.

2. I had to check before replying about `var` vs `let`. I seemed to have recalled — and MDN [confirmed my remembrance](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/let) — that `let` define scope-limited variables, instead of global-scope like `var` does by default. While I don't use same-name variables in my code here, I took it as a rule to define block-level variables with `let`. It seems a good rule to me, with what little I know of the mechanics behind programming language parsing.

3. Are you referring to `requestInterval`, the `rAF`-based timer that I included? If so, I merely copied it from Chris Coyier's post [here on CSS-Tricks](https://css-tricks.com/snippets/javascript/replacements-setinterval-using-requestanimationframe/). I've barely adjusted it and didn't actually look into the workings of the code itself. I have a personal timer library that utilizes `rAF` and seems to be doing a pretty good job, but I didn't want to burden OP's code additional files.

4. See above. I suspect that using an actual `rAF` timer library would do favors to the game's performance and usability, but I felt it inappropriate to try and shiv my own — or any other big — stuff into the code from where I was standing at the time.

5. On saving every tick: I was following the author's original design. Unsure of the ticksize itself or its purpose, I left everything as is, so as to not interfere with whatever plans OP might have had for the ticksize and the on-every-tick action. The actions of saving the version and the time played with every `save()` stem from this idea. I do see now that I could've implemented the save mechanic as a single-string elegant solution, but I'm not to tinker with the code longer. I feel like I've done my part. Your suggestions sound exactly reasonable, and it would be wise to implement them.

Glad you liked the data structure. Like I said, there's a case to be made against "god objects", and it *might* be wise (I say, knowing very little on the matter) to separate them into their own entities and glue them together where necessary. So far, all seems to be satisfactory, to a piece of software of such a small size where polling a single object doesn't do that much harm.

**Comment by FirebrandCoding** [comment]
1. You were talking about caching the UI reference rather than the values, which is what I was referring to. I was trying to set up a `timeCache` object which would hold the last known changes to `time` (the main god object). With any change to `time` compared with `timeCache`, an update to layout would be issued, so as to no call draw every \~17 ms. There are object difference calculation functions available online, which is how I tried to implement it.

2. The replies about `let` opened my eyes to a problem I kept having as a just-starting programmer (the `let` vs `var` in a loop variable declaration), so thanks for that. `let` vs `var` seems to be a good topic to read up on.

3. Yours seems a reasonable approach. It's important to remember that we're discussing aspects of gamecrafting in JS that Phantasy is only going to learn about, so if you could provide commentary on how that very concise piece of code works, it would be an improvement for everyone.

I seem to recall the problem with god objects is the additional time it takes to survey the object for whatever method you're looking for. I'm no expert, however, so you're better off deferring to someone with actual knowledge of how JS works. I remain wary of the god object pattern because I was told to by people with presumably better knowledge on the matter. So far, the game and its `time` seem to be doing okay.

**Pull request closed without merging**
